### ISSUE TITLE
CLCellProtocol item属性 get 永远返回nil问题

### ISSUE THREAD

**Issue by 1xiaocainiao** [JmoVxia/CLDemo#10]
item需要存储，这里永远return了nil,导致cell里面无法正常获取数据

private var xoAssociationKey: UInt8 = 0

var item: T? {
        get {
            return objc_getAssociatedObject(self, &xoAssociationKey) as? T
        }
        set(newValue) {
            objc_setAssociatedObject(self, &xoAssociationKey, newValue, objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }

**Comment by JmoVxia** [comment]
协议默认实现是nil，对应的cell去实现协议中的 ` var item: T?`
