### ISSUE TITLE
弹窗PopupManager.dismiss和dismissAll会有偶发性崩溃❌

### ISSUE THREAD

**Issue by kimplwjf** [JmoVxia/CLDemo#11]
### 友盟捕捉到的线上崩溃日志，本地测试怎么测都无问题，不知大佬可否指点下，是我调用问题还是？

![image](https://user-images.githubusercontent.com/50983330/204956218-4d466178-b45e-458f-872c-cf85fa0942da.png)
![image](https://user-images.githubusercontent.com/50983330/204956246-15a0f524-67b7-4d7b-bc81-27da1f08706a.png)

**Comment by JmoVxia** [comment]
代码没有上下文无从查看，猜测可能是信号量引起线程问题
`Demo`中不是最新代码，最新代码已经更新，请自行查看

**Comment by kimplwjf** [comment]
好的，感谢大佬

> 代码没有上下文无从查看，猜测可能是信号量引起线程问题 `Demo`中不是最新代码，最新代码已经更新，请自行查看
