### ISSUE TITLE
podinstall报错

### ISSUE THREAD

**Issue by xiweiLee** [JmoVxia/CLDemo#5]
[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/xj/m57_s4rx18nbmfqkmrm09c8c0000gn/T/d20190725-66922-1x38cti --template= --single-branch --depth 1 --branch v1.0.2

Cloning into '/var/folders/xj/m57_s4rx18nbmfqkmrm09c8c0000gn/T/d20190725-66922-1x38cti'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by JmoVxia** [comment]
已经移除pod屏蔽
