### ISSUE TITLE
CLPasswordInputView移植到我的项目里面崩溃了

### ISSUE THREAD

**Issue by jolincheng** [JmoVxia/CLDemo#6]
![1572952225000](https://tiantong-1259630769.image.myqcloud.com/image/2019/11/05/9aa6dbb0a3.jpg)
![1572952262982](https://tiantong-1259630769.image.myqcloud.com/image/2019/11/05/e0d95ee21d.jpg)

**Comment by jolincheng** [comment]
[https://tiantong-1259630769.image.myqcloud.com/image/2019/11/05/9aa6dbb0a3.jpg](url)

**Comment by jolincheng** [comment]
[图片1](https://tiantong-1259630769.image.myqcloud.com/image/2019/11/05/9aa6dbb0a3.jpg)

**Comment by jolincheng** [comment]
[图片2](https://tiantong-1259630769.image.myqcloud.com/image/2019/11/05/e0d95ee21d.jpg)

**Comment by JmoVxia** [comment]
https://stackoverflow.com/questions/41054274/uitextview-make-application-crash-when-becomefirstresponder-called/41056269

http://zkforever.cn/2017/05/15/%E8%AF%A1%E5%BC%82%E9%94%99%E8%AF%AF%E8%A7%A3%E5%86%B3/

**Comment by jolincheng** [comment]
inputview名字重合了，已经解决了，谢谢了
